#!/usr/bin/env sh

if [[ -z $1 || -z $2 || -z $3 ]]; then
    echo "img2vid IN_PATTERN DST [FPS]"
else
    IN_PATTERN=$1
    DST=$2
    FPS=${3:-30}

    ffmpeg -pattern_type glob -i "$IN_PATTERN" -c:v libx264 -r $FPS -pix_fmt yuv420p $DST
fi
