#!/usr/bin/env sh

intizim() {
    zsh -c "source ${ZIM_HOME}/zimfw.zsh init -q"
}

# Download zimfw plugin manager if missing.
if [ ! -e ${ZIM_HOME}/zimfw.zsh ]; then
    curl \
        -fsSL \
        --create-dirs \
        -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh

    intizim
else
    # Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
    if [ ${ZDOTDIR}/zimrc -nt ${ZIM_HOME}/init.zsh ]; then
        intizim   
    fi
fi

