#!/usr/bin/env sh

# Install some packages first
sudo pacman -Syy qemu-full virt-manager virt-viewer dnsmasq vde2 bridge-utils openbsd-netcat
sudo systemctl enable --now libvirtd.service
sudo usermod -aG libvirt $USER
sudo systemctl restart libvirtd.service

echo -e "\n\nUncomment these two lines in the file /etc/libvirt/libvirtd.conf\n\nunix_sock_group = 'libvirt'\nunix_sock_rw_perms = '0770'\n"
echo -e "\n\nAdd this line to the file /etc/libvirt/network.conf\n\nfirewall_backend='iptables'"


