#!/bin/zsh

alacritty -e sh -c '
  pid=$(ps -eo pid,cmd --sort=-%mem | fzf --header="Select a process to kill" --preview="echo {}" | awk "{print \$1}")
  if [ -n "$pid" ]; then
    kill -9 "$pid"
  fi
'
