#!/usr/bin/env bash

FILE=$XDG_CONFIG_HOME/packages/arch/conda.csv
if ! [ -f $FILE ]; then
    exit 0
fi

DST="$HOME/.local/bin"
if ! [ -z $1 ]; then
    DST=$1
fi
mkdir -p $DST


# Read the file line by line
while IFS= read -r LINE; do
    PKG=$(echo $LINE | cut -d ',' -f 2 - | xargs)
    ln -sf $HOME/.local/src/anaconda3/bin/$PKG $DST/$PKG
done < "$FILE"

