#!/usr/bin/env bash

PTH_VRS=$(echo $PATH)

IFS=':'
read -ra PTH_VRS_LST <<< $PTH_VRS

echo "╭───────────────────────────────────────────────────────────────────────────╮"

for P in ${PTH_VRS_LST[@]}; do
    printf "│ 󰑢  %-70s │\n" "$P"
done

echo "╰───────────────────────────────────────────────────────────────────────────╯"
