#!/usr/bin/env sh

CWDR=$(pwd)

# replace the bare repository
echo "[1 of 3]: cloning the bare repository..."
cd $HOME/downloads
git clone git@github.com:ramyamounir/rmos --bare .rmos
if [ $? -ne 0 ]; then
    exit 0
fi

cd $HOME
rm -rf .rmos
mv $HOME/downloads/.rmos .

# configure git
echo "[2 of 3]: configuring the bare repository..."
git --git-dir $HOME/.rmos --work-tree $HOME config --local status.showUntrackedFiles yes
git --git-dir $HOME/.rmos --work-tree $HOME config --local pull.rebase off

# reset local changes
echo "[3 of 3]: resetting local changes..."
git --git-dir $HOME/.rmos --work-tree $HOME restore --staged .
git --git-dir $HOME/.rmos --work-tree $HOME checkout .

setpermissions

echo "Done."
cd $CWDR
