#!/usr/bin/env sh

CWDR=`pwd`

# replace the bare repository
echo "[1 of 3]: cloning the bare repository..."
cd $HOME/downloads
git clone git@github.com:sujaltv/tvsos --bare .tvsos
if [ $? -ne 0 ]; then
    exit 0
fi

cd $HOME
rm -rf .tvsos
mv $HOME/downloads/.tvsos .

# configure git
echo "[2 of 3]: configuring the bare repository..."
git --git-dir $HOME/.tvsos --work-tree $HOME config --local status.showUntrackedFiles no
git --git-dir $HOME/.tvsos --work-tree $HOME config --local pull.rebase off

# reset local changes
echo "[3 of 3]: resetting local changes..."
git --git-dir $HOME/.tvsos --work-tree $HOME restore --staged .
git --git-dir $HOME/.tvsos --work-tree $HOME checkout .

setpermissions

echo "Done."
cd $CWDR
