#!/usr/bin/env sh

git clone git@github.com:ramyamounir/rmss.git $HOME/.local/src/rmss

# start nginx
if command -v nginx &> /dev/null; then
    sudo systemctl enable --now nginx
fi

# start docker
if command -v docker &> /dev/null; then
    sudo systemctl enable --now docker
fi

# change ownership of mounted storage
sudo chown -R ramy:ramy /data

# Symlink RMSS
ln -s $HOME/.local/src/rmss/scripts/rmss $HOME/.config/scripts/rmss

# Issue certificates
rmss get-cert

