#!/bin/sh

DMENU_OPTIONS=`dwm -m`

# A dmenu wrapper script for system functions.
case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

case "$(printf "🔒 lock\n🚪 leave dwm\n🐻 quit\n🔃 reboot\n🖥️ shutdown\n" | dmenu $DMENU_OPTIONS -i -p 'Action: ')" in
	'🔒 lock') slock ;;
	'🚪 leave dwm') kill -TERM "$(pgrep -u "$USER" "\bdwm$")" ;;
	'🐻 quit') loginctl terminate-session $XDG_SESSION_ID ;;
	'🔃 reboot') $ctl reboot ;;
	'🖥️ shutdown') $ctl poweroff ;;
	*) exit 1 ;;
esac
