#!/usr/bin/env bash

read -p "Are you sure [y/n]? " SURE

if [[ "$SURE" != "y" && "$SURE" != "Y" ]]; then
    exit 0;
fi

# delete GPG keys
gpg --batch --yes --delete-secret-keys $(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2);

# cleanup files
rm -rf \
    $GNUPGHOME/private-keys-*.d \
    $GNUPGHOME/pubring.kbx* \
    $GNUPGHOME/random_seed \
    $GNUPGHOME/tofu.db \
    $GNUPGHOME/trustdb.gpg \
    $GNUPGHOME/.\#*;

# restart GPG agent
gpgconf --kill gpg-agent;
gpg-connect-agent reloadAgent /bye;
