#!/bin/sh

if [ -f "$XDG_DATA_HOME/screenlayout.sh" ]; then
  bash "$XDG_DATA_HOME/screenlayout.sh"
else
  xrandr --dpi 96
fi

# wallpaper settings
setbg $HOME/.local/wallpapers/ 			# set the background with the `setbg` script

# key remaps
remaps

xrdb -merge $XDG_CONFIG_HOME/x11/XResources

command -v dunst &> /dev/null && dunst    # dunst notification system

xcompmgr -c -C -t-0 -l-0 -r0 -o.5          # x compositor
