#!/bin/sh

DMENU_OPTIONS=`dwm -m`
ITEMS="$(pass show)"

OPTIONS=""
while IFS= read -r LINE; do
    read -ra TOKENS <<< $LINE
    OPTIONS="$OPTIONS${TOKENS[@]:1}\n"
done <<< ${ITEMS[@]:1}

echo -e $OPTIONS
CHOICE=$(printf "$OPTIONS" | dmenu $DMENU_OPTIONS -i -p "")

pass -c $CHOICE
