#!/usr/bin/env sh

NOTIFY_WHEN_FULL=0

# Defaults if env vars are not set
BATTERY_DIR="${BATTERY_DIR:-/sys/class/power_supply/BAT0}"
BATTERY_PREFIX="${BATTERY_PREFIX:-charge}"

battery_notify() {
    local battery_dir="$1"
    local percentage="$2"

    if [ "$(cat "$battery_dir/status")" = "Discharging" ]; then
        if [ "$percentage" -le 10 ]; then
            notify-send \
                "Battery low" \
                "Battery charge at $percentage%" \
                --urgency critical \
                --icon=/usr/share/icons/Adwaita/32x32/status/battery-level-10-charging-symbolic.symbolic.png
        fi
    else
        if [ "$NOTIFY_WHEN_FULL" -eq 1 ] && [ "$percentage" -ge 95 ]; then
            notify-send \
                "Battery sufficient" \
                "Battery charge at $percentage%" \
                --urgency low \
                --icon=/usr/share/icons/Adwaita/32x32/status/battery-level-100-charged-symbolic.symbolic.png
        fi
    fi
}

show_battery() {
    local battery_dir="$1"
    local prefix="$2"

    local now_file="$battery_dir/${prefix}_now"
    local full_file="$battery_dir/${prefix}_full"
    local status_file="$battery_dir/status"

    if [ -f "$now_file" ] && [ -f "$full_file" ]; then
        charge_now=$(cat "$now_file")
        charge_full=$(cat "$full_file")
        charge_status=$(cat "$status_file")

        percentage=$((100 * charge_now / charge_full))

        if [ "$charge_status" = "Discharging" ]; then
            echo -e " $percentage%"
        else
            echo -e " 󰚥 $percentage%"
        fi

        battery_notify "$battery_dir" "$percentage"
    fi
}

show_battery "$BATTERY_DIR" "$BATTERY_PREFIX"
