#!/usr/bin/env sh

WIFI_ACTIVE=0
WIRED_ACTIVE=0

if command -v nmcli > /dev/null 2>&1; then
    WIFI_ACTIVE=`nmcli con show --active | grep wifi | wc -l`
    WIRED_ACTIVE=`nmcli con show --active | grep ethernet | wc -l`
fi

[[ $WIFI_ACTIVE -ge 1 ]] && echo -e ""

[[ $WIRED_ACTIVE -ge 1 ]] && echo -e "󰈀"

