command: "python benchmarks/run.py -e {exp}"

paths:
    results_cache: /home/ramy/tbp/results/monty/projects/benchmarks_comparisons
    result_filename: eval_stats.csv
    results_dir: /home/ramy/tbp/results/monty/projects/evidence_eval_runs/logs

branches:
    - name: "main"
      rerun: false

    - name: "evidence_slope_tracker"
      rerun: false

experiments:
    - name: "unsupervised_inference_distinctobj_dist_agent"
      rerun: true

    - name: "unsupervised_inference_distinctobj_surf_agent"
      rerun: false
