#!/bin/sh

# Prompt the user for the number of nodes
read -p "Enter the number of nodes: " nodes

# Prompt the user for the number of GPUs
read -p "Enter the number of GPUs per node: " gpus

# Prompt the user for the number of CPUs
read -p "Enter the number of CPUs per node: " cpus

# Prompt the user for the amount of memory
read -p "Enter the amount of CPU memory (in GB): " memory

# Prompt the user for the time limit (in days-hours)
read -p "Enter the time limit (in days-hours): " time

# Prompt the user for the partition
read -p "Enter the partition (optional; default = Contributors): " partition

# Prompt the user for the node name
read -p "Enter the node names (optional): " nodelist

# Prompt the user for the job name
read -p "Enter the job name (optional; default = tvs): " jname

if [ -z $partition ]; then
    partition="Contributors"
fi

if [ -z $jname ]; then
    jname="tvs-interactive"
fi

# Submit the interactive job to Slurm
if [ -n "$nodelist" ]; then
  srun \
	  --job-name $jname \
	  --nodes=$nodes \
	  --ntasks-per-node=$cpus \
	  --gres=gpu:$gpus \
	  --mem=$memory \
	  --partition=$partition \
	  --time=$time \
	  --nodelist=$nodelist \
	  --pty "$SHELL"
else
  srun \
	  --job-name $jname \
	  --nodes=$nodes \
	  --ntasks-per-node=$cpus \
	  --gres=gpu:$gpus \
	  --mem=$memory \
	  --partition=$partition \
	  --time=$time \
	  --pty "$SHELL"
fi
