#!/bin/bash

DMENU_OPTIONS=`dwm -m`

# Get list of running processes (excluding the header and this script)
ps -eo pid,comm --sort=-%mem | grep -v $$ | sed 1d |
  dmenu $DMENU_OPTIONS -m -i -l 20 -p "Kill which process?" |
  awk '{print $1}' |
  xargs -r kill -9
