#!/usr/bin/env sh

DMENU_OPTIONS=`dwm -m`

OPTIONS=(
    "USF"
    "NordVPN"
    "Off"
)

PROMPT=""
for O in "${OPTIONS[@]}"; do
    PROMPT="$PROMPT$O\n"
done

CHOICE=$(printf "$PROMPT" | dmenu $DMENU_OPTIONS -i)

case $CHOICE in
    ${OPTIONS[0]})
        nordvpn disconnect;
        echo -e "$(pass show emails/usf | tail -n 2 | head -n 1 | cut -d ':' -f 2 | xargs)\n$(pass show emails/usf | head -n 1)" | nmcli connection up usf --ask;
        notify-send -i "USF VPN" "Connected to VPN"
        ;;
    ${OPTIONS[1]})
        nmcli connect down usf;
        nordvpn connect;
        ;;
    ${OPTIONS[2]})
        nmcli connect down usf;
        nordvpn disconnect;
        notify-send -i "VPN" "Disconnected from VPN"
        ;;
    *)
        ;;
esac
